export const products = [
    {
        description: "update",
        images: ["/assests/Products/demo/demo1.png", "/assests/Products/demo/demo2.png", "/assests/Products/demo/demo3.png"],
        price: "25000",
        skuCode: "ss007",
        status: "Active",
        title: "New",
        tyreAspect: "Sturdo Passenger",
        tyreBrand: "ZXY",
        tyreSize: "1234/43",
        tyreType: "Type",
        tyreWidth: "123",
        vehicleBrand: "Maruti",
    },
    {
        description: "update",
        images: ["/assests/Products/demo/demo1.png", "/assests/Products/demo/demo2.png", "/assests/Products/demo/demo3.png"],
        price: "20000",
        skuCode: "ss007",
        status: "Active",
        title: "New",
        tyreAspect: "Sturdo Passenger",
        tyreBrand: "ZXY",
        tyreSize: "1234/43",
        tyreType: "Type",
        tyreWidth: "123",
        vehicleBrand: "Suzuki",
    },
    {
        description: "update",
        images: ["/assests/Products/demo/demo1.png", "/assests/Products/demo/demo2.png", "/assests/Products/demo/demo3.png"],
        price: "25000",
        skuCode: "ss007",
        status: "Active",
        title: "New",
        tyreAspect: "Sturdo Passenger",
        tyreBrand: "ZXY",
        tyreSize: "1234/43",
        tyreType: "Type",
        tyreWidth: "123",
        vehicleBrand: "MG",
    },
    {
        description: "update",
        images: ["/assests/Products/demo/demo1.png", "/assests/Products/demo/demo2.png", "/assests/Products/demo/demo3.png"],
        price: "25000",
        skuCode: "ss007",
        status: "Active",
        title: "New",
        tyreAspect: "Sturdo Passenger",
        tyreBrand: "ZXY",
        tyreSize: "1234/43",
        tyreType: "Type",
        tyreWidth: "123",
        vehicleBrand: "BMW",
    },
    {
        description: "update",
        images: ["/assests/Products/demo/demo1.png", "/assests/Products/demo/demo2.png", "/assests/Products/demo/demo3.png"],
        price: "25000",
        skuCode: "ss007",
        status: "Active",
        title: "New",
        tyreAspect: "Sturdo Passenger",
        tyreBrand: "ZXY",
        tyreSize: "1234/43",
        tyreType: "Type",
        tyreWidth: "123",
        vehicleBrand: "Tata",
    },
    {
        description: "update",
        images: ["/assests/Products/demo/demo1.png", "/assests/Products/demo/demo2.png", "/assests/Products/demo/demo3.png"],
        price: "25000",
        skuCode: "ss007",
        status: "Active",
        title: "New",
        tyreAspect: "Ccopia",
        tyreBrand: "ZXY",
        tyreSize: "1234/43",
        tyreType: "Type",
        tyreWidth: "123",
        vehicleBrand: "Honda",
    },
    {
        description: "update",
        images: ["/assests/Products/demo/demo1.png", "/assests/Products/demo/demo2.png", "/assests/Products/demo/demo3.png"],
        price: "25000",
        skuCode: "ss007",
        status: "Active",
        title: "New",
        tyreAspect: "Ccopia",
        tyreBrand: "ZXY",
        tyreSize: "1234/43",
        tyreType: "Type",
        tyreWidth: "123",
        vehicleBrand: "Maruti",
    },
]