import ServiceHero from '@/Components/Services/ServiceHero'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { serviceData } from '../../data'
import { useEffect, useState } from 'react'
import AllServices from '@/Components/Services/allServices'
import ServiceCard from '@/Components/Services/ServiceCard'

export default function Home() {
    const route = useRouter();
    // const { path } = router.query;
    const path = route.query.service

    const [data, setData] = useState(null);

    useEffect(() => {
        if (path) {
            const matchedService = serviceData.find((item) => item.id === path);
            if (matchedService) {
                setData(matchedService);
            } else {
            }
        }

    }, [path]);

    return (
        <>
            <Head>
                <title>{data ? data.service : 'Loading...'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <ServiceHero data={data} />
                <ServiceCard data={data} />
                <AllServices text={false}/>
            </>
        </>
    )
}
