import ServiceHero from '@/Components/Services/ServiceHero'
import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home() {
    const router = useRouter()

    // Get the current path
    const currentPath = router.asPath
    console.log("path", currentPath);
    return (
        <>
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <ServiceHero />
            </>
        </>
    )
}
