import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import HowWeWork from '@/Components/Home/HowWeWork'
import CarSection from '@/Components/Home/CarSection'
import TyreBrands from '@/Components/Home/TyreBrands'
import OurVision from '@/Components/Home/OurVision'
import Contact from '@/Components/Common/Contact'
import ServicesMain from '@/Components/Home/ServicesMain'
import Header from '@/Components/Home/Header'


export default function Home() {
  return (
    <>
      <Head>
        <title>Sangeetha tyres</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <ServicesMain />
        <HowWeWork />
        <CarSection />
        <TyreBrands />
        <OurVision />
        <Contact />
      </>
    </>
  )
}
