import Head from 'next/head'
import React from 'react'
import styles from '@/styles/Products/Product.module.css'
import Navbar from '@/Components/Common/Navbar'
import Footer from '@/Components/Common/Footer'
import ProductListing from '@/Components/Products/ProductListing'

const index = () => {
    return (
        <>
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                {/* <Navbar /> */}
                <div className={styles.banner}>
                    <h3>BRIDGESTONE TYRE CATEGORIES</h3>
                </div>
                <ProductListing />
                <Footer />
            </>
        </>
    )
}

export default index