import AddProduct from '@/Components/Admin/IndividualProduct'
import Head from 'next/head'
import styles from '@/styles/Admin/Dashboard.module.css'
import Product from '@/Components/Admin/Product'
import { PopupContext } from '@/Context'
import { useState } from 'react'
import AddItemPopup from '@/Components/Admin/AddItemPopup'


export default function Admin() {
  const [popupActive, setPopupActive] = useState(false)
  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PopupContext.Provider value={{ popupActive, setPopupActive }} >
        <div className={styles.adminDashboard}>
          <div className={styles.leftFilter}>

          </div>
          <div className={styles.rightDash}>
            <Product />
            {/* {popupActive ? <AddItemPopup /> : '' } */}
          </div>
        </div>
      </PopupContext.Provider>
    </>
  )
}
